version: '3'
services:
  dev: 
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/usr/app/frontend
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/usr/app/frontend
    command: ["npm", "run", "test"]
